### ISSUE TITLE
llvm-svn repo issue

### ISSUE THREAD

**Issue by sandikata** [kerberizer/llvm-svn#14]
libGL: dlopen /usr/lib32/xorg/modules/dri/radeonsi_dri.so failed (/usr/lib32/libgcc_s.so.1: version `GCC_7.0.0' not found (required by /usr/lib32/libLLVM-5.0svn.so))
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi

it missmatch and i have a lot of failures on system.
Because it looking for a gcc7 which is unavailable in archlinux repos.

Не открива въпросната версия gcc, няма я и в хранилищата на archlinux.
Някакви предложения ?

**Comment by kerberizer** [comment]
Discussed over IRC: resolved (was due to stale Arch mirrrors).
