### ISSUE TITLE
(on branch enh/lldb-svn) error from pacman file 'six.py' owned by 'lldb-svn' and 'python2-six'

### ISSUE THREAD

**Issue by aleden** [kerberizer/llvm-svn#16]
I get the following error when installing all the packages built by the enh/lldb-svn branch.

error: file owned by 'lldb-svn' and 'python2-six': 'usr/lib/python2.7/site-packages/six.py'

I assume that all we need to do is add python2-six as a dependency of lldb-svn, and then prevent lldb-svn from installing six.py?

**Comment by kerberizer** [comment]
This does indeed seems the way to go. Thank you!

**Comment by kerberizer** [comment]
Fixed by 8f9d5fdd35e8d77795b72cd3371e8818bc19d2c2.
