### ISSUE TITLE
repos.uni-plovdiv.net no have llvm-svn.db

### ISSUE THREAD

**Issue by hepha** [kerberizer/llvm-svn#20]
hello 
llvm-svn does not exist
[llvm-svn]
Server = https://repos.uni-plovdiv.net/archlinux/$repo/$arch

error: failed retrieving file 'llvm-svn.db' from repos.uni-plovdiv.net : The requested URL returned error: 404
error: failed to update llvm-svn (unexpected error)

**Comment by xDShot** [comment]
Change _https_ to _http_, so it appears in repo.

But there's a problem with pgp key now.

**Comment by kerberizer** [comment]
This was fixed long ago. Feel free to reopen if not the case.
