### ISSUE TITLE
llvm-ocaml-svn: installing ocaml (4.06.0-1) breaks dependency 'ocaml=4.05.0'

### ISSUE THREAD

**Issue by Tuerai** [kerberizer/llvm-svn#21]
Hello,

When running package updates today, it seems like the standard arch package for ocaml has been upgraded past the version that llvm-svn used when I last built it a few weeks ago.

[fury@hikari ~]$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: llvm-ocaml-svn: installing ocaml (4.06.0-1) breaks dependency 'ocaml=4.05.0'
[fury@hikari ~]$ sudo pacman -Qs ocaml
local/llvm-ocaml-svn 6.0.0svn_r321666-1
    OCaml bindings for LLVM
local/ocaml 4.05.0-1
    A functional language with OO extensions
local/ocaml-ctypes 0.11.5-1
    Library for binding to C libraries using pure OCaml

**Comment by kerberizer** [comment]
@Tuerai Sorry for not being able to respond earlier. I suppose you must've solved the problem in the meantime? (you'd typically need to rebuild your packages in a clean chroot—or use the binary repo)
