### ISSUE TITLE
Build fails on ocaml_doc

### ISSUE THREAD

**Issue by Oxalin** [kerberizer/llvm-svn#4]
When installing clang-svn or llvm-svn, the build process fails at 100% with the following message:
...
[100%] Building OCaml documentation for llvm_X86
Copying OCaml library component llvm_X86.cma to intermediate area
[100%] Building OCaml documentation for llvm_all_backends
Copying OCaml library component libllvm_X86.a to intermediate area
Copying OCaml library component llvm_all_backends.cma to intermediate area
Copying OCaml library component llvm_X86.cmxa to intermediate area
[100%] Building OCaml documentation for llvm_executionengine
Copying OCaml library component libllvm_all_backends.a to intermediate area
Copying OCaml library component llvm_X86.a to intermediate area
Copying OCaml library component llvm_all_backends.cmxa to intermediate area
File "/tmp/yaourt-tmp-ademers/aur-clang-svn/src/build/bindings/ocaml/executionengine/llvm_executionengine.ml", line 1:
Error: The files /usr/lib/ocaml/llvm_target.cmi and llvm_executionengine.cmi
       make inconsistent assumptions over interface Llvm_target
1 error(s) encountered
bindings/ocaml/executionengine/CMakeFiles/ocaml_llvm_executionengine.dir/build.make:104: recipe for target 'bindings/ocaml/executionengine/llvm_executionengine.odoc' failed
make[3]: **\* [bindings/ocaml/executionengine/llvm_executionengine.odoc] Error 1
make[3]: **\* Deleting file 'bindings/ocaml/executionengine/llvm_executionengine.odoc'
CMakeFiles/Makefile2:13441: recipe for target 'bindings/ocaml/executionengine/CMakeFiles/ocaml_llvm_executionengine.dir/all' failed
make[2]: **\* [bindings/ocaml/executionengine/CMakeFiles/ocaml_llvm_executionengine.dir/all] Error 2
make[2]: **\* Waiting for unfinished jobs....
Copying OCaml library component llvm_X86.cmi to intermediate area
Copying OCaml library component llvm_all_backends.a to intermediate area
Copying OCaml library component llvm_X86.cmx to intermediate area
Copying OCaml library component llvm_all_backends.cmi to intermediate area
[100%] Built target ocaml_llvm_X86
Copying OCaml library component llvm_all_backends.cmx to intermediate area
[100%] Built target ocaml_llvm_all_backends
CMakeFiles/Makefile2:51707: recipe for target 'docs/CMakeFiles/ocaml_doc.dir/rule' failed
make[1]: **\* [docs/CMakeFiles/ocaml_doc.dir/rule] Error 2
Makefile:10766: recipe for target 'ocaml_doc' failed
make: **\* [ocaml_doc] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build llvm-svn.
==> Restart building clang-svn ? [y/N]
==> ----------------------------------
==>

**Comment by kerberizer** [comment]
@Oxalin, either uninstall any previously installed llvm-ocaml package before building, or, _preferably_, [build in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot).

As explained in the [PKGBUILD comments](https://github.com/kerberizer/llvm-svn/blob/12a0519b65fbfe42c90344cc55f2d2c8ab7564fb/PKGBUILD#L163), 'Make sure that there isn't an incompatible llvm-ocaml package installed, or else the build will fail with "inconsistent assumptions over interface" errors.'

Please test again and close the issue if this solves the problem. Thanks for reporting.

**Comment by Oxalin** [comment]
Thanks, I had missed it. I'll try it later during the weekend.

**Comment by kerberizer** [comment]
Assumed solved by 59a1f4934baf13aa479a744c91ee668f8c456359. Closing.
